### ISSUE TITLE
Validator has no options to pass a path prefix and therefore is not usable with multiple routes

### ISSUE THREAD

**Issue by paulish** [BRIKEV/express-oas-validator#18]
When express routes are used like this:
```javascript
// authorization routines
app.use('/auth', require("./routes/auth"));
// user profile routines
app.use('/user', require("./routes/user"));
```

The validator fails to find the correct path since it uses `req.route.path` which returns only the the final path.

E.g. `/auth/login` request will have `/login` as `req.route.path` .

The solution is either use `req.baseUrl` together with `req.route.path` or to give an options to pass the baseUrl to validation methods.

**Comment by SBeyeMHP** [comment]
Can confirm.

Changing https://github.com/BRIKEV/express-oas-validator/blob/10e392ad2a55b22953b853aec2ee535bb4afb2f5/utils/index.js#L35 to `req.baseUrl + req.route.path` did solve it in this setup.

**Comment by kevinccbsg** [comment]
thanks for that info!! We will upload a release today 🚀
